version: 0.0
os: linux
files:
  - source: /
    destination: /home/webapp/laravel_portfolio/backend

permissions:
  - object: /home/webapp/laravel_portfolio/backend
    owner: webapp
    group: webapp

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 60
      runas: webapp
